modLoader="javafml"
loaderVersion="[43,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/MythicBotany/issues"

[[mods]]
modId="mythicbotany"
version="${file.jarVersion}"
displayName="MythicBotany"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicbotany"
updateJSONURL="https://assets.melanx.de/updates/mythicbotany.json"
authors="noeppi_noeppi, Contributors: MelanX"
description='''
Dive deeper into the world of botania.
'''

[[dependencies.mythicbotany]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.2-4.2.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="sandbox"
    mandatory=true
    versionRange="[1.19.2-1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botania"
    mandatory=true
    versionRange="[1.19.2-439,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19.2-77,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="jei"
    mandatory=false
    versionRange="[1.19.2-11.6.0.1015,)"
    ordering="NONE"
    side="CLIENT"
