modLoader="javafml"
loaderVersion="[40,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/MythicBotany/issues"

[[mods]]
modId="mythicbotany"
version="${file.jarVersion}"
displayName="MythicBotany"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicbotany"
updateJSONURL="https://assets.melanx.de/updates/mythicbotany.json"
authors="noeppi_noeppi, Contributors: MelanX"
description='''
Dive deeper into the world of botania.
'''

[[dependencies.mythicbotany]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.48,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.2-431,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.2-67,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="jei"
    mandatory=false
    versionRange="[1.18.2-9.7.0.180,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mythicbotany]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.15,)"
    ordering="NONE"
    side="BOTH"
