modLoader="javafml"
loaderVersion="[35,)"
license="APACHE-2.0"
issueTrackerURL="http://placeholder.invalid"

[[mods]]
modId="mythicbotany"
version="${file.jarVersion}"
displayName="MythicBotany"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicbotany"
updateJSONURL="https://assets.melanx.de/updates/mythicbotany.json"
authors="noeppi_noeppi, Contributors: MelanX"
description='''
Dive deeper into the world of botania.
'''

[[dependencies.mythicbotany]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botania"
    mandatory=true
    versionRange="[1.16.4-419,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-51,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="jei"
    mandatory=false
    versionRange="[1.16.1-7.0.0.6,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mythicbotany]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.76,)"
    ordering="NONE"
    side="BOTH"