modLoader="javafml"
loaderVersion="[39,)"
license="APACHE-2.0"
issueTrackerURL="http://placeholder.invalid"

[[mods]]
modId="mythicbotany"
version="${file.jarVersion}"
displayName="MythicBotany"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicbotany"
updateJSONURL="https://assets.melanx.de/updates/mythicbotany.json"
authors="noeppi_noeppi, Contributors: MelanX"
description='''
Dive deeper into the world of botania.
'''

[[dependencies.mythicbotany]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.76,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.1-429,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.1-65,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="jei"
    mandatory=false
    versionRange="[1.18.1-9.2.1.69,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mythicbotany]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.1.13,)"
    ordering="NONE"
    side="BOTH"